const QueryKeys = {
  list: 'systems/list',
  listWindow: 'systems/listWindow',
  details: 'systems/details',
  history: 'systems/history',
  patch: 'systems/patch',
  listSchedulerProfiles: 'systems/listScehdulerProfiles',
  createSystem: 'systems/createSystem',
  deleteSystem: 'systems/deleteSystem',
  shareSystemPublic: 'systems/shareSystemPublic',
  unShareSystemPublic: 'systems/unShareSystemPublic',
  createChildSystem: 'systems/createChildSystem',
  createUserCredential: 'systems/createUserCredential',
  removeUserCredential: 'systems/removeUserCredential',
  checkUserCredential: 'systems/checkUserCredential',
  getUserCredential: 'systems/getUserCredential',
  getUserPerms: 'systems/getUserPerms',
  userPermsMap: 'systems/userPermsMap',
  getGlobusAuthUrl: 'systems/getGlobusAuthUrl',
  generateGlobusTokens: 'systems/generateGlobusTokens',
  shareSystem: 'systems/shareSystem',
  unShareSystem: 'systems/unShareSystem',
  unlinkFromParent: 'systems/unlinkFromParent',
  grantUserPerms: 'systems/grantUserPerms',
  revokeUserPerms: 'systems/revokeUserPerms',
  changeOwner: 'systems/changeOwner',
  disableSystem: 'systems/disableSystem',
  enableSystem: 'systems/enableSystem',
  hostEval: 'systems/hostEval',
};

export default QueryKeys;
