export const TAPIS_SYSTEMS_LIST_REQUEST = 'TAPIS_SYSTEMS_LIST_REQUEST';
export const TAPIS_SYSTEMS_LIST_SUCCESS = 'TAPIS_SYSTEMS_LIST_SUCCESS';
export const TAPIS_SYSTEMS_LIST_FAILURE = 'TAPIS_SYSTEMS_LIST_FAILURE';