# syntax=docker/dockerfile:1.7-labs
## ^ for --exclude on COPY
FROM node:22.4.0 as build-stage

RUN mkdir tapisui
WORKDIR /tapisui

# Copy the rest of the files
COPY \
  --exclude=./packages**node_modules* \
  --exclude=./.vscode \
  --exclude=./__pycache__ \
  --exclude=./__mocks__ \
  --exclude=./.github \
  --exclude=./build \
  --exclude=./deploy \
  ./ ./

  # Only in prod do we exclude prebuilt files
  # --exclude=**node_modules* \
  # --exclude=**dist* \
  # Still need this or we get a sha calc error, race condition?
  #--exclude=./packages**node_modules* \

# Install all files in the package json
RUN npm run init-project container

ENTRYPOINT ["npm", "run", "start-dev"]
