/* tslint:disable */
/* eslint-disable */
/**
 * Tenants API
 * Manage Tapis Tenants.
 *
 * The version of the OpenAPI document: 1
 * Contact: cicsupport@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Owner
 */
export interface Owner {
    /**
     * Full name of the owner.
     * @type {string}
     * @memberof Owner
     */
    name: string;
    /**
     * Email address for the owner.
     * @type {string}
     * @memberof Owner
     */
    email: string;
    /**
     * The owner's institution.
     * @type {string}
     * @memberof Owner
     */
    institution: string;
    /**
     * The time the client was created.
     * @type {string}
     * @memberof Owner
     */
    create_time?: string;
    /**
     * The time the client was last updated.
     * @type {string}
     * @memberof Owner
     */
    last_update_time?: string;
}

export function OwnerFromJSON(json: any): Owner {
    return OwnerFromJSONTyped(json, false);
}

export function OwnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Owner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'institution': json['institution'],
        'create_time': !exists(json, 'create_time') ? undefined : json['create_time'],
        'last_update_time': !exists(json, 'last_update_time') ? undefined : json['last_update_time'],
    };
}

export function OwnerToJSON(value?: Owner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'email': value.email,
        'institution': value.institution,
        'create_time': value.create_time,
        'last_update_time': value.last_update_time,
    };
}


