/* tslint:disable */
/* eslint-disable */
/**
 * Tenants API
 * Manage Tapis Tenants.
 *
 * The version of the OpenAPI document: 1
 * Contact: cicsupport@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Tenant
 */
export interface Tenant {
    /**
     * The unique identifier for the tenant.
     * @type {string}
     * @memberof Tenant
     */
    tenant_id: string;
    /**
     * The base URL for the tenant.
     * @type {string}
     * @memberof Tenant
     */
    base_url: string;
    /**
     * The site for which the tenant belongs.
     * @type {string}
     * @memberof Tenant
     */
    site_id: string;
    /**
     * The resolvable location of the token service for the tenant.
     * @type {string}
     * @memberof Tenant
     */
    token_service: string;
    /**
     * The resolvable location of the security kernel for the tenant.
     * @type {string}
     * @memberof Tenant
     */
    security_kernel: string;
    /**
     * The resolvable location of the authenticator for the tenant.
     * @type {string}
     * @memberof Tenant
     */
    authenticator: string;
    /**
     * The email address of the primary owner and contact for the tenant.
     * @type {string}
     * @memberof Tenant
     */
    owner: string;
    /**
     * The username of the user that is automatically assigned the tenant_admin role by the Security Kernel.
     * @type {string}
     * @memberof Tenant
     */
    admin_user?: string;
    /**
     * The list of services that are automatically granted the token_generator role for this tenant by the Security Kernel.
     * @type {Array<string>}
     * @memberof Tenant
     */
    token_gen_services?: Array<string>;
    /**
     * The unique identifier for the LDAP object for service accounts in the tenant.
     * @type {string}
     * @memberof Tenant
     */
    service_ldap_connection_id?: string;
    /**
     * The unique identifier for the LDAP object for user accounts in the tenant.
     * @type {string}
     * @memberof Tenant
     */
    user_ldap_connection_id?: string;
    /**
     * The public key that should be used to validate the signatures of JWTs associated with the tenant.
     * @type {string}
     * @memberof Tenant
     */
    public_key?: string;
    /**
     * A description of the tenant.
     * @type {string}
     * @memberof Tenant
     */
    description?: string;
    /**
     * The time the client was created.
     * @type {string}
     * @memberof Tenant
     */
    create_time?: string;
    /**
     * The time the client was last updated.
     * @type {string}
     * @memberof Tenant
     */
    last_update_time?: string;
}

export function TenantFromJSON(json: any): Tenant {
    return TenantFromJSONTyped(json, false);
}

export function TenantFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tenant {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tenant_id': json['tenant_id'],
        'base_url': json['base_url'],
        'site_id': json['site_id'],
        'token_service': json['token_service'],
        'security_kernel': json['security_kernel'],
        'authenticator': json['authenticator'],
        'owner': json['owner'],
        'admin_user': !exists(json, 'admin_user') ? undefined : json['admin_user'],
        'token_gen_services': !exists(json, 'token_gen_services') ? undefined : json['token_gen_services'],
        'service_ldap_connection_id': !exists(json, 'service_ldap_connection_id') ? undefined : json['service_ldap_connection_id'],
        'user_ldap_connection_id': !exists(json, 'user_ldap_connection_id') ? undefined : json['user_ldap_connection_id'],
        'public_key': !exists(json, 'public_key') ? undefined : json['public_key'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'create_time': !exists(json, 'create_time') ? undefined : json['create_time'],
        'last_update_time': !exists(json, 'last_update_time') ? undefined : json['last_update_time'],
    };
}

export function TenantToJSON(value?: Tenant | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tenant_id': value.tenant_id,
        'base_url': value.base_url,
        'site_id': value.site_id,
        'token_service': value.token_service,
        'security_kernel': value.security_kernel,
        'authenticator': value.authenticator,
        'owner': value.owner,
        'admin_user': value.admin_user,
        'token_gen_services': value.token_gen_services,
        'service_ldap_connection_id': value.service_ldap_connection_id,
        'user_ldap_connection_id': value.user_ldap_connection_id,
        'public_key': value.public_key,
        'description': value.description,
        'create_time': value.create_time,
        'last_update_time': value.last_update_time,
    };
}


