export const TAPIS_VARIABLES_LIST_REQUEST = 'TAPIS_VARIABLES_LIST_REQUEST';
export const TAPIS_VARIABLES_LIST_SUCCESS = 'TAPIS_VARIABLES_LIST_SUCCESS';
export const TAPIS_VARIABLES_LIST_FAILURE = 'TAPIS_VARIABLES_LIST_FAILURE';