import React from 'react';
import { Help, HelpSection } from '@tapis/tapisui-common';

const ArchivesHelp: React.FC = () => {
  return (
    <Help title="Archives">
      <HelpSection>
        Archives serve as permanent storage for outputs generated by{' '}
        <b>Tasks</b> in a <b>Pipeline</b>.
      </HelpSection>
    </Help>
  );
};

export default ArchivesHelp;
