export const TAPIS_DEFAULT_FILES_LISTING_LIMIT = 1000;
export const TAPIS_DEFAULT_PROJECTS_LISTING_LIMIT = 100;
export const TAPIS_DEFAULT_SYSTEMS_LISTING_LIMIT = 100;
export const TAPIS_DEFAULT_APPS_LISTING_LIMIT = 100;
export const TAPIS_DEFAULT_JOBS_LISTING_LIMIT = 100;
