export declare const TAPIS_JOBS_SUBMIT_REQUEST = "TAPIS_JOBS_SUBMIT_REQUEST";
export declare const TAPIS_JOBS_SUBMIT_SUCCESS = "TAPIS_JOBS_SUBMIT_SUCCESS";
export declare const TAPIS_JOBS_SUBMIT_FAILURE = "TAPIS_JOBS_SUBMIT_FAILURE";
export declare const TAPIS_JOBS_SUBMIT_RESET = "TAPIS_JOBS_SUBMIT_RESET";
