export const TAPIS_FILES_LIST_REQUEST = 'TAPIS_FILES_LIST_REQUEST';
export const TAPIS_FILES_LIST_SUCCESS = 'TAPIS_FILES_LIST_SUCCESS';
export const TAPIS_FILES_LIST_FAILURE = 'TAPIS_FILES_LIST_FAILURE';