export declare const TAPIS_FILES_LIST_REQUEST = "TAPIS_FILES_LIST_REQUEST";
export declare const TAPIS_FILES_LIST_SUCCESS = "TAPIS_FILES_LIST_SUCCESS";
export declare const TAPIS_FILES_LIST_FAILURE = "TAPIS_FILES_LIST_FAILURE";
