export const TAPIS_JOBS_RETRIEVE_REQUEST = 'TAPIS_JOBS_RETRIEVE_REQUEST';
export const TAPIS_JOBS_RETRIEVE_SUCCESS = 'TAPIS_JOBS_RETRIEVE_SUCCESS';
export const TAPIS_JOBS_RETRIEVE_FAILURE = 'TAPIS_JOBS_RETRIEVE_FAILURE';