export declare const TAPIS_AUTH_LOGIN_REQUEST = "TAPIS_AUTH_LOGIN_REQUEST";
export declare const TAPIS_AUTH_LOGIN_SUCCESS = "TAPIS_AUTH_LOGIN_SUCCESS";
export declare const TAPIS_AUTH_LOGIN_FAILURE = "TAPIS_AUTH_LOGIN_FAILURE";
