export const TAPIS_INSTRUMENTS_LIST_REQUEST = 'TAPIS_INSTRUMENTS_LIST_REQUEST';
export const TAPIS_INSTRUMENTS_LIST_SUCCESS = 'TAPIS_INSTRUMENTS_LIST_SUCCESS';
export const TAPIS_INSTRUMENTS_LIST_FAILURE = 'TAPIS_INSTRUMENTS_LIST_FAILURE';
export const TAPIS_SELECT_INSTRUMENT = "TAPIS_SELECT_INSTRUMENT";