export declare const TAPIS_APPS_LIST_REQUEST = "TAPIS_APPS_LIST_REQUEST";
export declare const TAPIS_APPS_LIST_SUCCESS = "TAPIS_APPS_LIST_SUCCESS";
export declare const TAPIS_APPS_LIST_FAILURE = "TAPIS_APPS_LIST_FAILURE";
