export const TAPIS_SITES_LIST_REQUEST = 'TAPIS_SITES_LIST_REQUEST';
export const TAPIS_SITES_LIST_SUCCESS = 'TAPIS_SITES_LIST_SUCCESS';
export const TAPIS_SITES_LIST_FAILURE = 'TAPIS_SITES_LIST_FAILURE';