export const TAPIS_PROJECTS_LIST_REQUEST = 'TAPIS_PROJECTS_LIST_REQUEST';
export const TAPIS_PROJECTS_LIST_SUCCESS = 'TAPIS_PROJECTS_LIST_SUCCESS';
export const TAPIS_PROJECTS_LIST_FAILURE = 'TAPIS_PROJECTS_LIST_FAILURE';