export const TAPIS_MEASUREMENTS_LIST_REQUEST = 'TAPIS_MEASUREMENTS_LIST_REQUEST';
export const TAPIS_MEASUREMENTS_LIST_SUCCESS = 'TAPIS_MEASUREMENTS_LIST_SUCCESS';
export const TAPIS_MEASUREMENTS_LIST_FAILURE = 'TAPIS_MEASUREMENTS_LIST_FAILURE';