export declare const TAPIS_JOBS_LIST_REQUEST = "TAPIS_JOBS_LIST_REQUEST";
export declare const TAPIS_JOBS_LIST_SUCCESS = "TAPIS_JOBS_LIST_SUCCESS";
export declare const TAPIS_JOBS_LIST_FAILURE = "TAPIS_JOBS_LIST_FAILURE";
