export declare const TAPIS_REDUX_API_REQUEST = "TAPIS_REDUX_API_REQUEST";
export declare const TAPIS_REDUX_API_SUCCESS = "TAPIS_REDUX_API_SUCCESS";
export declare const TAPIS_REDUX_API_FAILURE = "TAPIS_REDUX_API_FAILURE";
