export declare const TAPIS_SYSTEMS_LIST_REQUEST = "TAPIS_SYSTEMS_LIST_REQUEST";
export declare const TAPIS_SYSTEMS_LIST_SUCCESS = "TAPIS_SYSTEMS_LIST_SUCCESS";
export declare const TAPIS_SYSTEMS_LIST_FAILURE = "TAPIS_SYSTEMS_LIST_FAILURE";
